server {
    listen 80;
    server_name localhost;

    location = / {
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
    }

    location /notes {
        proxy_pass http://backend:5000/notes;
        proxy_set_header Host $host;
    }

    location / {
        return 404;
    }
}