name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  code-analysis-and-tests:
    name: Linting and Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lab3/requirements.txt
          
          sudo apt-get install -y shellcheck
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      - name: Run Linters (Flake8, Hadolint, Shellcheck)
        run: |
          cd lab3
          echo "Running flake8..."
          flake8 app.py tests_app.py --max-line-length=150
          echo "Running hadolint..."
          hadolint Dockerfile
          echo "Running shellcheck..."
          shellcheck setup.sh

      - name: Run Pytest and Coverage
        run: |
          cd lab3
          echo '{"db_host": "localhost", "db_port": 5432, "db_name": "test", "db_user": "test", "db_password": "123", "app_port": 5000}' > config.json
          pytest tests_app.py --cov=app --cov-fail-under=40 --cov-report=xml --cov-report=term
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: lab3/coverage.xml

  build-and-push-image:
    name: Build and Push Docker Image
    needs: code-analysis-and-tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=sha-${{ github.sha }}
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./lab3
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-and-verify:
    name: Deploy to Target Node and Verify
    needs: build-and-push-image
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Application via SSH
        env:
          DB_PASS: ${{ secrets.DB_PASSWORD }}
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          sed -i 's|\${GITHUB_REPOSITORY}|'"$REPO_LOWER"'|g' lab3/docker-compose.yml
          sed -i 's|\$GITHUB_REPOSITORY|'"$REPO_LOWER"'|g' lab3/docker-compose.yml
          
          scp -o StrictHostKeyChecking=no lab3/docker-compose.yml operator@192.168.56.101:/home/operator/mywebapp/
          
          ssh -o StrictHostKeyChecking=no operator@192.168.56.101 << EOF
          cd /home/operator/mywebapp
          
          echo '{
              "db_host": "host.docker.internal",
              "db_port": 5432,
              "db_name": "notes_db",
              "db_user": "notes_user",
              "db_password": "${DB_PASS}",
              "app_port": 5000
          }' > config.json
          
          docker compose pull web
          sudo systemctl restart mywebapp.service
          EOF

      - name: Verify Deployment
        run: |
          echo "Waiting for service to start..."
          sleep 10
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.56.101/)
          
          if [ "$HTTP_STATUS" -eq 201 ]; then
            echo "Verification successful: Service returned 200 OK!"
            exit 0
          else
            echo "Verification failed: Service returned status $HTTP_STATUS"
            exit 1
          fi